// models/student_notes_sheet_model.js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const StudentNotesSchema = new Schema({
  grupo: String,
  codigo: Number,
  nombre: String,
  periodo: String,
  puesto: Number,
  promedio: Number,
  ciencias_naturales: Number,
  fisica: Number,
  quimica: Number,
  ciencias_politicas_economicas: Number,
  ciencias_sociales: Number,
  civica_y_constitucion: Number,
  educacion_artistica: Number,
  educacion_cristiana: Number,
  educacion_etica: Number,
  educacion_fisica: Number,
  filosofia: Number,
  idioma_extranjero: Number,
  lengua_castellana: Number,
  matematicas: Number,
  tecnologia: Number,
  observaciones_ciencias_naturales: String,
  observaciones_fisica: String,
  observaciones_quimica: String,
  observaciones_ciencias_politicas_economicas: String,
  observaciones_ciencias_sociales: String,
  observaciones_civica_y_constitucion: String,
  observaciones_educacion_artistica: String,
  observaciones_educacion_cristiana: String,
  observaciones_educacion_etica: String,
  observaciones_educacion_fisica: String,
  observaciones_filosofia: String,
  observaciones_idioma_extranjero: String,
  observaciones_lengua_castellana: String,
  observaciones_matematicas: String,
  observaciones_tecnologia: String,
  metas_ciencias_naturales: String,
  metas_fisica: String,
  metas_quimica: String,
  metas_ciencias_politicas_economicas: String,
  metas_ciencias_sociales: String,
  metas_civica_y_constitucion: String,
  metas_educacion_artistica: String,
  metas_educacion_cristiana: String,
  metas_educacion_etica: String,
  metas_educacion_fisica: String,
  metas_filosofia: String,
  metas_idioma_extranjero: String,
  metas_lengua_castellana: String,
  metas_matematicas: String,
  metas_tecnologia: String,
  rep_eva_ciencias_naturales: String,
  rep_eva_fisica: String,
  rep_eva_quimica: String,
  rep_eva_ciencias_politicas_economicas: String,
  rep_eva_ciencias_sociales: String,
  rep_eva_civica_y_constitucion: String,
  rep_eva_educacion_artistica: String,
  rep_eva_educacion_cristiana: String,
  rep_eva_educacion_etica: String,
  rep_eva_educacion_fisica: String,
  rep_eva_filosofia: String,
  rep_eva_idioma_extranjero: String,
  rep_eva_lengua_castellana: String,
  rep_eva_matematicas: String,
  rep_eva_tecnologia: String

});

module.exports = mongoose.model('StudentNotes', StudentNotesSchema);
